services:

  backend:
    # will build ./backend/Dockerfile
    build: ./backend
    ports:
      - "8000:8000"


  frontend:
    # will build ./ipuatsons/Dockerfile
    build: ./ipuatsons
    ports:
     - "80:80"
    volumes:
     - .:/code