apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
spec:
  storageClassName:  manual
  volumeName: mypv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
