apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-share
spec:
  storageClassName: manual
  capacity:
    storage: 500Gi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteMany
  nfs:
    server: 161.246.5.77
    path: "/volume1/ipautsons"
