apiVersion: batch/v1

kind: Job

metadata:

  name: testpixel03

spec:

  template:

    spec:

      containers:

      - name: testpixel03

        image: suteesaraphan27/pixel
        volumeMounts:
            - name: myvolume
              mountPath: /www

        command: ["python","pixel.py","1","/www/ea"]

      restartPolicy: Never
      volumes:
      - name: myvolume
        persistentVolumeClaim: 
          claimName: mypvc
